# ?? Database ??????????????????????????????????????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/game_system
spring.datasource.username=root
spring.datasource.password=Sqzimp0#40...||WOOFLOL

# ?? Mail (Gmail example ? replace with your credentials) ??????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arpedjeyescomen@gmail.com
spring.mail.password=yetreqhhdbhkwzhs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ?? Server ????????????????????????????????????????????????????????????????
server.port=8080